import { CurrentVehicleStatusV3 } from '../JaguarLandRover/ServiceTypes'
import { CurrentVehicleStatus } from './Types'

const emptyVehicleStatus: CurrentVehicleStatus = {
    vehicleStatus: {
        core: {
            TU_STATUS_PRIMARY_VOLT: '',
            TU_STATUS_PRIMARY_CHARGE_PERCENT: '',
            DOOR_IS_ALL_DOORS_LOCKED: '',
            TU_STATUS_GSM_MODEM: '',
            TU_STATUS_IMEI: '',
            CLIMATE_STATUS_TIMER1_DAY: '',
            BATTERY_STATUS: '',
            WASHER_FLUID_WARN: '',
            DOOR_FRONT_LEFT_POSITION: '',
            TU_STATUS_SLEEP_CYCLES_START_TIME: '',
            DOOR_REAR_RIGHT_POSITION: '',
            TU_STATUS_GNSS_ANTENNA: '',
            ENGINE_COOLANT_TEMP: '',
            DISTANCE_TO_EMPTY_FUEL: '',
            CLIMATE_STATUS_REMAINING_RUNTIME: '',
            ODOMETER_MILES_RESOLUTION: '',
            SERVICE_MODE_START: '',
            TYRE_STATUS_REAR_LEFT: '',
            ODOMETER_MILES: '',
            TU_STATUS_SECONDARY_VOLT: '',
            ARM_REST_SECOND_ROW_STATUS: '',
            SRS_STATUS: '',
            DOOR_REAR_RIGHT_LOCK_STATUS: '',
            IS_PANIC_ALARM_TRIGGERED: '',
            DOOR_FRONT_RIGHT_POSITION: '',
            BRAKE_FLUID_WARN: '',
            DRV_SEAT_THIRD_ROW_INHIBITION: '',
            DOOR_REAR_LEFT_LOCK_STATUS: '',
            TU_STATUS_MOBILE_PHONE_CONNECTED: '',
            TU_STATUS_SW_VERSION_CONFIG: '',
            EXT_OIL_LEVEL_WARN: '',
            DRV_SEAT_THIRD_ROW_STATUS: '',
            TU_STATUS_MIC: '',
            TU_STATUS_POWER: '',
            DOOR_ENGINE_HOOD_POSITION: '',
            TRANSPORT_MODE_START: '',
            EXT_BULB_STATUS_LEFT_TURN_ANY: '',
            ENG_COOLANT_LEVEL_WARN: '',
            WINDOW_FRONT_RIGHT_STATUS: '',
            WINDOW_REAR_RIGHT_STATUS: '',
            TU_STATUS_INT_RTC: '',
            TYRE_STATUS_FRONT_LEFT: '',
            THEFT_ALARM_STATUS: '',
            IS_SUNROOF_OPEN: '',
            ODOMETER: '',
            EXT_KILOMETERS_TO_SERVICE: '',
            TU_STATUS_DAYS_SINCE_GNSS_FIX: '',
            PAS_SEAT_SECOND_ROW_STATUS: '',
            TU_STATUS_BUTTONS: '',
            PAS_SEAT_THIRD_ROW_STATUS: '',
            VEHICLE_STATE_TYPE: '',
            DOOR_ENGINE_HOOD_LOCK_STATUS: '',
            TYRE_STATUS_FRONT_RIGHT: '',
            PRIVACY_SWITCH: '',
            TU_STATUS_EXT_POWER: '',
            CLIMATE_STATUS_TIMER1_MINUTE: '',
            LATEST_COMPLETE_CONFIG_UPDATE: '',
            TU_STATUS_HANDSET: '',
            BRAZIL_EVENT_MODE: '',
            IS_CRASH_SITUATION: '',
            DOOR_FRONT_RIGHT_LOCK_STATUS: '',
            TYRE_PRESSURE_REAR_RIGHT: '',
            TU_STATUS_CONFIG_VERSION: '',
            CLIMATE_STATUS_TIMER2_DAY: '',
            DOOR_FRONT_LEFT_LOCK_STATUS: '',
            WINDOW_REAR_LEFT_STATUS: '',
            PAS_SEAT_FIRST_ROW_INHIBITION: '',
            DRV_SEAT_SECOND_ROW_STATUS: '',
            TU_STATUS_EXT_HANDSFREE: '',
            PAS_SEAT_FIRST_ROW_STATUS: '',
            CLIMATE_STATUS_FFH_REMAINING_RUNTIME: '',
            CLIMATE_STATUS_VENTING_TIME: '',
            TYRE_PRESSURE_FRONT_RIGHT: '',
            FUEL_LEVEL_PERC: '',
            CLIMATE_STATUS_TIMER2_MONTH: '',
            PAS_SEAT_THIRD_ROW_INHIBITION: '',
            DOOR_IS_BOOT_LOCKED: '',
            TU_STATUS_SW_VERSION_SECONDARY: '',
            DOOR_BOOT_POSITION: '',
            IS_HEAD_LIGHTS_ON: '',
            TU_STATUS_CRASH_INPUT: '',
            SERVICE_MODE_STOP: '',
            TYRE_PRESSURE_FRONT_LEFT: '',
            CLIMATE_STATUS_TIMER2_MINUTE: '',
            IS_CAB_OPEN: '',
            TU_STATUS_USES_EXTERNAL_GNSS: '',
            ODOMETER_METER_RESOLUTION: '',
            TU_STATUS_GSM_EXT_ANTENNA: '',
            CLIMATE_STATUS_TIMER2_HOUR: '',
            ARM_REST_SECOND_ROW_INHIBITION: '',
            ODOMETER_METER: '',
            BATTERY_VOLTAGE: '',
            TU_STATUS_SPEAKER: '',
            TRANSPORT_MODE_STOP: '',
            ENGINE_BLOCK: '',
            TYRE_PRESSURE_REAR_LEFT: '',
            CLIMATE_STATUS_TIMER_ACTIVATION_STATUS: '',
            TU_STATUS_GNSS: '',
            TU_STATUS_SW_VERSION_MAIN: '',
            TU_STATUS_INT_POWER: '',
            TU_STATUS_HW_VERSION: '',
            PAS_SEAT_SECOND_ROW_INHIBITION: '',
            WINDOW_FRONT_LEFT_STATUS: '',
            DOOR_REAR_LEFT_POSITION: '',
            CLIMATE_STATUS_OPERATING_STATUS: '',
            CLIMATE_STATUS_TIMER1_HOUR: '',
            CLIMATE_STATUS_TIMER1_MONTH: '',
            TU_STATUS_SERIAL_NUMBER: '',
            TYRE_STATUS_REAR_RIGHT: '',
            TU_ACTIVATION_STATUS: '',
            DRV_SEAT_SECOND_ROW_INHIBITION: '',
            DOOR_BOOT_LOCK_STATUS: '',
            TU_STATUS_CAN: ''
        },
        ev: {
            EV_NEXT_DEPARTURE_TIMER_IS_SET: '',
            EV_RANGE_ON_BATTERY_MILES: '',
            EV_CHARGING_STATUS: '',
            EV_RANGE_COMFORTx10: '',
            EV_IS_PLUGGED_IN: '',
            EV_CHARGING_METHOD: '',
            EV_RANGE_VSC_VEH_ACCEL_FACTOR: '',
            EV_PERMANENT_MAX_SOC_CHARGE_SETTING_CHOICE: '',
            EV_RANGE_VSC_REGEN_ENERGY_AVAILABLEx100: '',
            EV_NEXT_DEPARTURE_TIMER_TIME_HOUR: '',
            EV_CHARGING_RATE_KM_PER_HOUR: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD1: '',
            EV_RANGE_VSC_RANGE_MAP_REFACTR_COMF: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD2: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD3: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD4: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD5: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD6: '',
            EV_RANGE_VSC_HV_BATTERY_CONSUMPTION_SPD7: '',
            EV_STATE_OF_CHARGE: '',
            EV_RANGE_VSC_REVISED_HV_BATT_ENERGYx100: '',
            EV_NEXT_DEPARTURE_TIMER_DATE_YEAR: '',
            EV_IS_CHARGING: '',
            EV_RANGE_VSC_HV_ENERGY_TIME_PENx100: '',
            EV_PRECONDITION_PRIORITY_SETTING: '',
            EV_BATTERY_PRECONDITIONING_STATUS: '',
            EV_NEXT_DEPARTURE_TIMER_DATE_DAY: '',
            EV_PHEV_RANGE_COMBINED_KM: '',
            EV_RANGE_VSC_RANGE_MAP_REFACTR_ECO: '',
            EV_MINUTES_TO_BULK_CHARGED: '',
            EV_CHARGING_MODE_CHOICE: '',
            EV_ENERGY_CONSUMED_LAST_CHARGE_KWH: '',
            EV_PHEV_RANGE_COMBINED_MILES: '',
            EV_RANGE_ON_BATTERY_KM: '',
            EV_RANGE_PREDICT_STATUS: '',
            EV_RANGE_VSC_INITIAL_HV_BATT_ENERGYx100: '',
            EV_RANGE_VSC_HV_ENERGY_DESCENTx10: '',
            EV_NEXT_DEPARTURE_TIMER_TIME_MINUTE: '',
            EV_ONE_OFF_MAX_SOC_CHARGE_SETTING_CHOICE: ''
        }
    },
    vehicleAlerts: [],
    lastUpdatedTime: new Date()
}

interface VehicleStatusMapper {
    map: (data: CurrentVehicleStatusV3) => CurrentVehicleStatus
}

const vehicleStatusMapper: VehicleStatusMapper = {
    map: (data: CurrentVehicleStatusV3): CurrentVehicleStatus => {        
        let mapped = { ...emptyVehicleStatus }

        type CoreStatusKey = keyof typeof mapped.vehicleStatus.core
        data.vehicleStatus.coreStatus.map(element => (mapped.vehicleStatus.core[element.key as CoreStatusKey] = element.value))

        type EvStatusKey = keyof typeof mapped.vehicleStatus.ev
        data.vehicleStatus.evStatus.map(element => (mapped.vehicleStatus.ev[element.key as EvStatusKey] = element.value))

        return mapped
    }
}

export {
    VehicleStatusMapper,
    vehicleStatusMapper
}
